<Project>
	<Target Name="CopyProjectReferencesToPackage" DependsOnTargets="BuildOnlySettings;ResolveReferences">
		<ItemGroup>
			<!-- Filter out unnecessary files -->
			<_ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')-&gt;WithMetadataValue('PrivateAssets', 'All'))"/>
		</ItemGroup>
		<!-- Print batches for debug purposes -->
		<Message Text="Batch for .nupkg: ReferenceCopyLocalPaths = @(_ReferenceCopyLocalPaths), ReferenceCopyLocalPaths.DestinationSubDirectory = %(_ReferenceCopyLocalPaths.DestinationSubDirectory) Filename = %(_ReferenceCopyLocalPaths.Filename) Extension = %(_ReferenceCopyLocalPaths.Extension)" Importance="High" Condition="'@(_ReferenceCopyLocalPaths)' != ''"/>
		<ItemGroup>
			<!-- Add file to package with consideration of sub folder. If empty, the root folder is chosen. -->
			<BuildOutputInPackage Include="@(_ReferenceCopyLocalPaths)" TargetPath="%(_ReferenceCopyLocalPaths.DestinationSubDirectory)"/>
		</ItemGroup>
	</Target>
	<PropertyGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<!-- Microsoft Testing Platform -->
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<!-- Code Coverage -->
		<CollectCoverage Condition="'$(CollectCoverage)' == ''">false</CollectCoverage>
		<CoverletOutputFormat Condition="'$(CoverletOutputFormat)' == ''">opencover</CoverletOutputFormat>
		<CoverletOutput Condition="'$(CoverletOutput)' == '' and '$(GITHUB_WORKSPACE)' != ''">$(GITHUB_WORKSPACE)/coverage/</CoverletOutput>
		<CoverletOutput Condition="'$(CoverletOutput)' == ''">$(MSBuildProjectDirectory)/coverage/</CoverletOutput>
		<ExcludeByFile>**/*.Designer.cs,**/*.g.cs</ExcludeByFile>
		<ExcludeByAttribute>GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
		<IncludeTestAssembly>false</IncludeTestAssembly>
	</PropertyGroup>
	<ItemGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
		<Using Include="Xunit"/>
	</ItemGroup>
	<ItemGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<!-- xUnit Tests-->
	<ItemGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
		<PackageReference Include="Microsoft.TestPlatform.TestHost"/>
		<PackageReference Include="Microsoft.NET.Test.Sdk"/>
		<PackageReference Include="Microsoft.AspNetCore.TestHost"/>
		<PackageReference Include="xunit.v3"/>
		<PackageReference Include="xunit.analyzers"/>
		<PackageReference Include="xunit.runner.visualstudio"/>
		<PackageReference Include="coverlet.msbuild"/>
		<PackageReference Include="FluentAssertions"/>
	</ItemGroup>
</Project>
